In [14]:
class account:
    def __init__(self, number, name):
        self.number = number
        self.name = name
        self.balance = 0
    def deposit(self, amount):
        if amount <= 0 :
            raise ValueError("must be positive")
        self.balance+=amount
    def withdraw(self, amount):
        if amount <= self.balance:
            self.balance-=amount
        else:
            raise ValueError("not enough")
acct1 = account('123-456', 'Justin')
acct1.deposit(1000)
acct1.withdraw(300)
print(acct1.balance)


700


In [16]:
import random
random.seed(10)

four_unif_randoms = [random.random() for _ in range(4)]
four_unif_randoms


[0.5714025946899135,
 0.4288890546751146,
 0.5780913011344704,
 0.20609823213950174]

In [4]:
import numpy as np
a = np.arange(20)
a = a.reshape(4,5)
print(a)
a.ndim
a.shape
a.size
a.dtype

[[ 0  1  2  3  4]
 [ 5  6  7  8  9]
 [10 11 12 13 14]
 [15 16 17 18 19]]


dtype('int64')

In [6]:
raw = [1,2,3,4,5]
a = np.array(raw)
a
new_raw = ([1,2,3,4,5],[6,7,8,9,10])
b = np.array(new_raw)
b

array([[ 1,  2,  3,  4,  5],
       [ 6,  7,  8,  9, 10]])

In [9]:
d = (4,5)
np.zeros(d)
np.ones(d)


array([[1., 1., 1., 1., 1.],
       [1., 1., 1., 1., 1.],
       [1., 1., 1., 1., 1.],
       [1., 1., 1., 1., 1.]])

In [20]:
b = np.matrix('1.0 2.0 ; 3.0 4.0')
b
a = np.arange(2,45,3).reshape(5,3)
a
np.count_nonzero(a)
a = np.mat(a)
print(a)

[[ 2  5  8]
 [11 14 17]
 [20 23 26]
 [29 32 35]
 [38 41 44]]


In [21]:
np.linspace(0,3,12)

array([0.        , 0.27272727, 0.54545455, 0.81818182, 1.09090909,
       1.36363636, 1.63636364, 1.90909091, 2.18181818, 2.45454545,
       2.72727273, 3.        ])

In [23]:
my_arr = np.arange(1000000)
my_arr2 = my_arr*2
my_arr2

array([      0,       2,       4, ..., 1999994, 1999996, 1999998])