Pandas -- from python data analysis

In [3]:
import pandas as pd
from pandas import Series, DataFrame
 
## dict to pd.Series
sdata = {'Ohio':35000, 'Texas':71000, 'Oregon': 16000, 'Utah':5000}
series = pd.Series(sdata)
print(series)

## we can search by states
states = ['California', 'Ohio', 'Oregon', 'Texas']
series2 = pd.Series(sdata, states)
print(series2)

Ohio      35000
Texas     71000
Oregon    16000
Utah       5000
dtype: int64
California        NaN
Ohio          35000.0
Oregon        16000.0
Texas         71000.0
dtype: float64


In [4]:
## setting up DataFrame
data = {'state': ['Ohio', 'Ohio', 'Ohio', 'Nevada', 'Nevada', 'Nevada'],
        'year': [2000, 2001, 2002, 2001, 2002, 2003],
        'pop': [1.5, 1.7, 3.6, 2.4, 2.9, 3.2]}
frame = pd.DataFrame(data)
print(frame)

    state  year  pop
0    Ohio  2000  1.5
1    Ohio  2001  1.7
2    Ohio  2002  3.6
3  Nevada  2001  2.4
4  Nevada  2002  2.9
5  Nevada  2003  3.2


In [5]:
## import functions
data2 = pd.Series(['blue', 'purple', 'yellow'], index = [0,2,4])
data2.index.name = 'index'
print(data2)
data2new = data2.reindex(range(6), method = 'ffill')
print(data2new)

index
0      blue
2    purple
4    yellow
dtype: object
index
0      blue
1      blue
2    purple
3    purple
4    yellow
5    yellow
dtype: object


In [6]:
## set a DataFrame
import numpy as np
frame = pd.DataFrame(np.arange(9).reshape((3,3)), index = ['a', 'c', 'd'], columns = ['Ohio', 'Texas', 'California'])
print(frame)

## data reshape
frame1 = frame.reindex(['a', 'b', 'c', 'd'])
print(frame1)
states = ['Texas', 'Utah', 'California']
frame2 = frame.reindex(columns = states)
print(frame2)


   Ohio  Texas  California
a     0      1           2
c     3      4           5
d     6      7           8
   Ohio  Texas  California
a   0.0    1.0         2.0
b   NaN    NaN         NaN
c   3.0    4.0         5.0
d   6.0    7.0         8.0
   Texas  Utah  California
a      1   NaN           2
c      4   NaN           5
d      7   NaN           8


In [7]:
## same result using loc and iloc
print(f'Use loc \n', frame.loc[['a', 'c']])
print(f'Use iloc \n', frame.iloc[[0,1]])

Use loc 
    Ohio  Texas  California
a     0      1           2
c     3      4           5
Use iloc 
    Ohio  Texas  California
a     0      1           2
c     3      4           5


Calculate between Series and DataFrame


In [8]:
arr = np.arange(12.).reshape([3,4])
print(arr)
print(arr[0])
print(arr-arr[0])  ## broadcasting

[[ 0.  1.  2.  3.]
 [ 4.  5.  6.  7.]
 [ 8.  9. 10. 11.]]
[0. 1. 2. 3.]
[[0. 0. 0. 0.]
 [4. 4. 4. 4.]
 [8. 8. 8. 8.]]


In [9]:
frame = pd.DataFrame(np.arange(12.).reshape([4,3]), columns = list('bde'), index = ['Utah', 'Ohio', 'Texas', 'Oregon'])
print(f'frame:\n', frame)
series = frame.loc['Utah']
print(f'series:\n', series)
print(f'minus:\n', frame - series) ## solution is same as above.

frame:
           b     d     e
Utah    0.0   1.0   2.0
Ohio    3.0   4.0   5.0
Texas   6.0   7.0   8.0
Oregon  9.0  10.0  11.0
series:
 b    0.0
d    1.0
e    2.0
Name: Utah, dtype: float64
minus:
           b    d    e
Utah    0.0  0.0  0.0
Ohio    3.0  3.0  3.0
Texas   6.0  6.0  6.0
Oregon  9.0  9.0  9.0


Apply in DataFrame


In [10]:
frame2 = pd.DataFrame(np.random.randn(4, 3), columns = list('abc'), index = ['Utah', 'Ohio', 'Texas', 'Oregon'])
print(f'frame2:\n', frame2)
abs_frame2 = np.abs(frame2)
print(f'abs of frame2:\n', abs_frame2)

## starting using apply
f = lambda x: x.max()-x.min() 
print(f'apply of rows\n', abs_frame2.apply(f))
print(f'apply of columns\n', abs_frame2.apply(f, axis = 'columns'))

## starting using applymap
format = lambda x: '%.2f' % x ## 四捨五入到小數點第二位
print(f'applymap\n', frame2.applymap(format))

frame2:
                a         b         c
Utah    1.229506  1.336899  1.755845
Ohio    1.099168 -0.239368  1.228524
Texas  -0.275849  0.039735  0.204034
Oregon -0.078148 -0.554657  0.012077
abs of frame2:
                a         b         c
Utah    1.229506  1.336899  1.755845
Ohio    1.099168  0.239368  1.228524
Texas   0.275849  0.039735  0.204034
Oregon  0.078148  0.554657  0.012077
apply of rows
 a    1.151358
b    1.297164
c    1.743768
dtype: float64
apply of columns
 Utah      0.526339
Ohio      0.989156
Texas     0.236114
Oregon    0.542580
dtype: float64
applymap
             a      b     c
Utah     1.23   1.34  1.76
Ohio     1.10  -0.24  1.23
Texas   -0.28   0.04  0.20
Oregon  -0.08  -0.55  0.01


Sort of DataFrame


In [11]:
object = pd.Series(range(4), index = ['d', 'a', 'c', 'b'])
print(f'sort of object: \n', object.sort_index())

## 沿特定軸排序
frame3 = pd.DataFrame(np.arange(12).reshape([2,6]), index = ['two', 'one'], columns = ['d', 'a', 'b', 'c', 'e', 'f'])
print(frame3.sort_index())
print(frame3.sort_index(axis = 1)) ## axis: 0 for 'rows', 1 for 'columns'
print(frame3.sort_index(axis = 0))
print(frame3.sort_index(axis = 1, ascending = False))

sort of object: 
 a    1
b    3
c    2
d    0
dtype: int64
     d  a  b  c   e   f
one  6  7  8  9  10  11
two  0  1  2  3   4   5
     a  b  c  d   e   f
two  1  2  3  0   4   5
one  7  8  9  6  10  11
     d  a  b  c   e   f
one  6  7  8  9  10  11
two  0  1  2  3   4   5
      f   e  d  c  b  a
two   5   4  0  3  2  1
one  11  10  6  9  8  7


repeated categories on index


In [12]:
obj = pd.Series(range(5), index = ['a', 'a', 'b', 'b', 'c'])
print(obj)

## is index unique or not
obj.index.is_unique

a    0
a    1
b    2
b    3
c    4
dtype: int64


False

Reduction or summary statistics

In [13]:
df = pd.DataFrame([[1.4, np.nan], [7.1, -4.5],
                   [np.nan, np.nan], [0.75, -1.3]],
                   index = ['a', 'b', 'c', 'd'],
                   columns = ['one', 'two'])
print(df)
print(f'sum of column\n', df.sum())
print(f'sum of rows\n', df.sum(axis = 1))
print(f'which index as the max value\n', df.idxmax())
print(f'cumulative summary\n', df.cumsum())
print(f'lots of values\n', df.describe())

    one  two
a  1.40  NaN
b  7.10 -4.5
c   NaN  NaN
d  0.75 -1.3
sum of column
 one    9.25
two   -5.80
dtype: float64
sum of rows
 a    1.40
b    2.60
c    0.00
d   -0.55
dtype: float64
which index as the max value
 one    b
two    d
dtype: object
cumulative summary
     one  two
a  1.40  NaN
b  8.50 -4.5
c   NaN  NaN
d  9.25 -5.8
lots of values
             one       two
count  3.000000  2.000000
mean   3.083333 -2.900000
std    3.493685  2.262742
min    0.750000 -4.500000
25%    1.075000 -3.700000
50%    1.400000 -2.900000
75%    4.250000 -2.100000
max    7.100000 -1.300000


Correlation coefficients and covariance

In [18]:
import pandas_datareader.data as web

all_data ={ticker: web.get_data_yahoo(ticker)
            for ticker in ['AAPL', 'IBM', 'MSFT', 'GOOG']}
price = pd.DataFrame({ticker: data['Adj Close'] for ticker, data in all_data.items()})
volume = pd.DataFrame({ticker: data['Volume'] for ticker, data in all_data.items()})

## calculate the price change
returns = price.pct_change()
returns.tail()

## calculate corr
print(f'corr of returns\n', returns['MSFT'].corr(returns['GOOG']))
print(f'cov of returns\n', returns['MSFT'].cov(returns['GOOG']))

corr of returns
 0.7842635031043915
cov of returns
 0.00026757445119193274
