Pandas -- from python data analysis

In [2]:
import pandas as pd
from pandas import Series, DataFrame
 
## dict to pd.Series
sdata = {'Ohio':35000, 'Texas':71000, 'Oregon': 16000, 'Utah':5000}
series = pd.Series(sdata)
print(series)

## we can search by states
states = ['California', 'Ohio', 'Oregon', 'Texas']
series2 = pd.Series(sdata, states)
print(series2)

Ohio      35000
Texas     71000
Oregon    16000
Utah       5000
dtype: int64
California        NaN
Ohio          35000.0
Oregon        16000.0
Texas         71000.0
dtype: float64


In [3]:
## setting up DataFrame
data = {'state': ['Ohio', 'Ohio', 'Ohio', 'Nevada', 'Nevada', 'Nevada'],
        'year': [2000, 2001, 2002, 2001, 2002, 2003],
        'pop': [1.5, 1.7, 3.6, 2.4, 2.9, 3.2]}
frame = pd.DataFrame(data)
print(frame)

    state  year  pop
0    Ohio  2000  1.5
1    Ohio  2001  1.7
2    Ohio  2002  3.6
3  Nevada  2001  2.4
4  Nevada  2002  2.9
5  Nevada  2003  3.2


In [4]:
## import functions
data2 = pd.Series(['blue', 'purple', 'yellow'], index = [0,2,4])
data2.index.name = 'index'
print(data2)
data2new = data2.reindex(range(6), method = 'ffill')
print(data2new)

index
0      blue
2    purple
4    yellow
dtype: object
index
0      blue
1      blue
2    purple
3    purple
4    yellow
5    yellow
dtype: object


In [5]:
## set a DataFrame
import numpy as np
frame = pd.DataFrame(np.arange(9).reshape((3,3)), index = ['a', 'c', 'd'], columns = ['Ohio', 'Texas', 'California'])
print(frame)

## data reshape
frame1 = frame.reindex(['a', 'b', 'c', 'd'])
print(frame1)
states = ['Texas', 'Utah', 'California']
frame2 = frame.reindex(columns = states)
print(frame2)


   Ohio  Texas  California
a     0      1           2
c     3      4           5
d     6      7           8
   Ohio  Texas  California
a   0.0    1.0         2.0
b   NaN    NaN         NaN
c   3.0    4.0         5.0
d   6.0    7.0         8.0
   Texas  Utah  California
a      1   NaN           2
c      4   NaN           5
d      7   NaN           8


In [6]:
## same result using loc and iloc
print(f'Use loc \n', frame.loc[['a', 'c']])
print(f'Use iloc \n', frame.iloc[[0,1]])

Use loc 
    Ohio  Texas  California
a     0      1           2
c     3      4           5
Use iloc 
    Ohio  Texas  California
a     0      1           2
c     3      4           5


Calculate between Series and DataFrame

In [9]:
arr = np.arange(12.).reshape([3,4])
print(arr)
print(arr[0])
print(arr-arr[0])  ## broadcasting

[[ 0.  1.  2.  3.]
 [ 4.  5.  6.  7.]
 [ 8.  9. 10. 11.]]
[0. 1. 2. 3.]
[[0. 0. 0. 0.]
 [4. 4. 4. 4.]
 [8. 8. 8. 8.]]


In [14]:
frame = pd.DataFrame(np.arange(12.).reshape([4,3]), columns = list('bde'), index = ['Utah', 'Ohio', 'Texas', 'Oregon'])
print(f'frame:\n', frame)
series = frame.loc['Utah']
print(f'series:\n', series)
print(f'minus:\n', frame - series) ## solution is same as above.

frame:
           b     d     e
Utah    0.0   1.0   2.0
Ohio    3.0   4.0   5.0
Texas   6.0   7.0   8.0
Oregon  9.0  10.0  11.0
series:
 b    0.0
d    1.0
e    2.0
Name: Utah, dtype: float64
minus:
           b    d    e
Utah    0.0  0.0  0.0
Ohio    3.0  3.0  3.0
Texas   6.0  6.0  6.0
Oregon  9.0  9.0  9.0


Apply in DataFrame

In [21]:
frame2 = pd.DataFrame(np.random.randn(4, 3), columns = list('abc'), index = ['Utah', 'Ohio', 'Texas', 'Oregon'])
print(f'frame2:\n', frame2)
abs_frame2 = np.abs(frame2)
print(f'abs of frame2:\n', abs_frame2)

## starting using apply
f = lambda x: x.max()-x.min() 
print(f'apply of rows\n', abs_frame2.apply(f))
print(f'apply of columns\n', abs_frame2.apply(f, axis = 'columns'))

## starting using applymap
format = lambda x: '%.2f' % x ## 四捨五入到小數點第二位
print(f'applymap\n', frame2.applymap(format))

frame2:
                a         b         c
Utah    0.052409  0.213128 -1.910567
Ohio    1.501926 -0.761608  0.150579
Texas   0.373973  1.037272 -0.084109
Oregon -0.288374  1.038656  2.412914
abs of frame2:
                a         b         c
Utah    0.052409  0.213128  1.910567
Ohio    1.501926  0.761608  0.150579
Texas   0.373973  1.037272  0.084109
Oregon  0.288374  1.038656  2.412914
apply of rows
 a    1.449517
b    0.825528
c    2.328805
dtype: float64
apply of columns
 Utah      1.858158
Ohio      1.351347
Texas     0.953163
Oregon    2.124539
dtype: float64
applymap
             a      b      c
Utah     0.05   0.21  -1.91
Ohio     1.50  -0.76   0.15
Texas    0.37   1.04  -0.08
Oregon  -0.29   1.04   2.41


Sort of DataFrame

In [33]:
object = pd.Series(range(4), index = ['d', 'a', 'c', 'b'])
print(f'sort of object: \n', object.sort_index())

## 沿特定軸排序
frame3 = pd.DataFrame(np.arange(12).reshape([2,6]), index = ['two', 'one'], columns = ['d', 'a', 'b', 'c', 'e', 'f'])
print(frame3.sort_index())
print(frame3.sort_index(axis = 1)) ## axis: 0 for 'rows', 1 for 'columns'
print(frame3.sort_index(axis = 0))
print(frame3.sort_index(axis = 1, ascending = False))

sort of object: 
 a    1
b    3
c    2
d    0
dtype: int64
     d  a  b  c   e   f
one  6  7  8  9  10  11
two  0  1  2  3   4   5
     a  b  c  d   e   f
two  1  2  3  0   4   5
one  7  8  9  6  10  11
     d  a  b  c   e   f
one  6  7  8  9  10  11
two  0  1  2  3   4   5
      f   e  d  c  b  a
two   5   4  0  3  2  1
one  11  10  6  9  8  7
